version: 2
jobs:
  build:
    docker:
      - image: golang:1.11.5
    steps:
      - checkout
      - run:
          name: "Install HUGO"
          command: |
            url="https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_extended_0.53_Linux-64bit.tar.gz"
            curl -sSL -o- $url | tar zx -C /usr/local/bin hugo
      - run: hugo
      - add_ssh_keys:
          fingerprints:
            - "b4:b6:be:eb:7b:9b:04:9a:3f:1f:50:8f:58:e0:b8:15"
      - run: '[ "${CIRCLE_BRANCH}" = "master" ] && ./bin/deploy || true'
