name: Deploy contents to Amazon S3

on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Install hugo and aws-cli
      id: setup-environment
      run: |
        sudo apt-get install -y python3-setuptools

        pip3 install awscli --upgrade --user

        curl -sSL -o- https://github.com/gohugoio/hugo/releases/download/v0.57.1/hugo_extended_0.57.1_Linux-64bit.tar.gz \
          | tar zx -C $HOME/.local/bin hugo

    - name: Build and deploy contents
      id: build-and-deploy
      env:
        CONTENT_BUCKET_NAME: ${{ secrets.CONTENT_BUCKET_NAME }}
      run: |
        $HOME/.local/bin/hugo
        if [ "$GITHUB_REF" = "refs/heads/master" ]; then
          $HOME/.local/bin/aws s3 sync ./public "s3://${CONTENT_BUCKET_NAME}"
        else
          $HOME/.local/bin/aws s3 sync --dryrun ./public "s3://${CONTENT_BUCKET_NAME}"
        fi
